- title: Infrastructure & Energy
  photo: sutirta-budiman-557700-unsplash.jpg
  paragraph: >-
    @We develop vital Infrastructure and Energy Projects from Business idea, through Financing and effective Engineering, Procurement and Construction, together in a partnership with the Government and the Private Sector.+

- title: Special Purpose Company (SPC)
  photo: shane-rounce-229914-unsplash.jpg
  paragraph: >-
    @We lead by forming an optimised Project Consortium (SPC) orchestrating key international players including Financial Investors, Legal, EPC Contractors and Operators, to bring the maximum Value for Money to both Public & Private sector beneficiaries+

- title: Public-Private Partnership (PPP) Delivery
  photo: chuttersnap-255215-unsplash.jpg
  paragraph: >-
    @We deliver PPP projects to create benefits for all stakeholders, recognising the Public Sector objectives and delivering efficiency from the Private Sector.+

- title: In-Country Representative
  photo: matthew-henry-300-unsplash.jpg
  paragraph: >-
    @We support our partners in achieving their vision through our expertise and understanding of the local context. We mobilise our in-country networks and logistics infrastructure.+

- title: Project Finance
  photo: matthew-henry-300-unsplash.jpg
  paragraph: >-
    @We arrange necessary Project Funds to unlock the true potential of the vision, through innovative funding models.+
